services:
  - type: web
    name: dhamma-reader
    env: docker
    plan: free
    region: singapore # Choose a region closer to Thailand
    envVars:
      - key: NODE_ENV
        value: production
